In [1]:
import pandas as pd

In [2]:
pwd

'C:\\Users\\Trivikram'

In [2]:
df=pd.read_csv("adult.data",header=None,names=['Age','Workplace','fnlwgt','education','education num','marital-stauts','occupation','relationship','race','sex','captial gain','capital loss','hours per week','native country','Salaray'])
df

,Age,Workplace,fnlwgt,education,education num,marital-stauts,occupation,relationship,race,sex,captial gain,capital loss,hours per week,native country,Salaray
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
12,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
14,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
16,25,Self-emp-not-inc,176756,HS-grad,9,Never-married,Farming-fishing,Own-child,White,Male,0,0,35,United-States,<=50K
17,32,Private,186824,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,United-States,<=50K
18,38,Private,28887,11th,7,Married-civ-spouse,Sales,Husband,White,Male,0,0,50,United-States,<=50K
19,43,Self-emp-not-inc,292175,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,45,United-States,>50K
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32531,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32533,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32534,37,Private,179137,Some-college,10,Divorced,Adm-clerical,Unmarried,White,Female,0,0,39,United-States,<=50K
32535,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,34,Private,160216,Bachelors,13,Never-married,Exec-managerial,Not-in-family,White,Female,0,0,55,United-States,>50K
32537,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32540,45,State-gov,252208,HS-grad,9,Separated,Adm-clerical,Own-child,White,Female,0,0,40,United-States,<=50K
32541,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K
32542,72,?,129912,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,25,United-States,<=50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32544,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32546,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32547,43,Private,260761,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,Mexico,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32549,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32551,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K
32553,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32555,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [8]:
df.columns

Index(['Age', 'Workplace', 'fnlwgt', 'education', 'education num',
       'marital-stauts', 'occupation', 'relationship', 'race', 'sex',
       'captial gain', 'capital loss', 'hours per week', 'native country',
       'Salaray'],
      dtype='object')

In [9]:
df.size

488415

In [10]:
df.shape

(32561, 15)

In [11]:
df.shape[0]

32561

In [3]:
df['Age']

0        39
1        50
2        38
3        53
4        28
5        37
6        49
7        52
8        31
9        42
10       37
11       30
12       23
13       32
14       40
15       34
16       25
17       32
18       38
19       43
20       40
21       54
22       35
23       43
24       59
25       56
26       19
27       54
28       39
29       49
         ..
32531    30
32532    34
32533    54
32534    37
32535    22
32536    34
32537    30
32538    38
32539    71
32540    45
32541    41
32542    72
32543    45
32544    31
32545    39
32546    37
32547    43
32548    65
32549    43
32550    43
32551    32
32552    43
32553    32
32554    53
32555    22
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64

In [4]:
df.Age

0        39
1        50
2        38
3        53
4        28
5        37
6        49
7        52
8        31
9        42
10       37
11       30
12       23
13       32
14       40
15       34
16       25
17       32
18       38
19       43
20       40
21       54
22       35
23       43
24       59
25       56
26       19
27       54
28       39
29       49
         ..
32531    30
32532    34
32533    54
32534    37
32535    22
32536    34
32537    30
32538    38
32539    71
32540    45
32541    41
32542    72
32543    45
32544    31
32545    39
32546    37
32547    43
32548    65
32549    43
32550    43
32551    32
32552    43
32553    32
32554    53
32555    22
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64

In [23]:
df.iloc[2,0]

38

In [41]:
df[['Age','Workplace','education']]

       Age          Workplace      education
0       39          State-gov      Bachelors
1       50   Self-emp-not-inc      Bachelors
2       38            Private        HS-grad
3       53            Private           11th
4       28            Private      Bachelors
5       37            Private        Masters
6       49            Private            9th
7       52   Self-emp-not-inc        HS-grad
8       31            Private        Masters
9       42            Private      Bachelors
10      37            Private   Some-college
11      30          State-gov      Bachelors
12      23            Private      Bachelors
13      32            Private     Assoc-acdm
14      40            Private      Assoc-voc
15      34            Private        7th-8th
16      25   Self-emp-not-inc        HS-grad
17      32            Private        HS-grad
18      38            Private           11th
19      43   Self-emp-not-inc        Masters
20      40            Private      Doctorate
21      54            Private        HS-grad
22      35        Federal-gov            9th
23      43            Private           11th
24      59            Private        HS-grad
25      56          Local-gov      Bachelors
26      19            Private        HS-grad
27      54                  ?   Some-college
28      39            Private        HS-grad
29      49            Private        HS-grad
...    ...                ...            ...
32531   30                  ?      Bachelors
32532   34            Private      Doctorate
32533   54            Private      Bachelors
32534   37            Private   Some-college
32535   22            Private           12th
32536   34            Private      Bachelors
32537   30            Private        HS-grad
32538   38            Private      Bachelors
32539   71                  ?      Doctorate
32540   45          State-gov        HS-grad
32541   41                  ?        HS-grad
32542   72                  ?        HS-grad
32543   45          Local-gov     Assoc-acdm
32544   31            Private        Masters
32545   39          Local-gov     Assoc-acdm
32546   37            Private     Assoc-acdm
32547   43            Private        HS-grad
32548   65   Self-emp-not-inc    Prof-school
32549   43          State-gov   Some-college
32550   43   Self-emp-not-inc   Some-college
32551   32            Private           10th
32552   43            Private      Assoc-voc
32553   32            Private        Masters
32554   53            Private        Masters
32555   22            Private   Some-college
32556   27            Private     Assoc-acdm
32557   40            Private        HS-grad
32558   58            Private        HS-grad
32559   22            Private        HS-grad
32560   52       Self-emp-inc        HS-grad

[32561 rows x 3 columns]

In [38]:
df.iloc[:,[0,1,3]]

       Age          Workplace      education
0       39          State-gov      Bachelors
1       50   Self-emp-not-inc      Bachelors
2       38            Private        HS-grad
3       53            Private           11th
4       28            Private      Bachelors
5       37            Private        Masters
6       49            Private            9th
7       52   Self-emp-not-inc        HS-grad
8       31            Private        Masters
9       42            Private      Bachelors
10      37            Private   Some-college
11      30          State-gov      Bachelors
12      23            Private      Bachelors
13      32            Private     Assoc-acdm
14      40            Private      Assoc-voc
15      34            Private        7th-8th
16      25   Self-emp-not-inc        HS-grad
17      32            Private        HS-grad
18      38            Private           11th
19      43   Self-emp-not-inc        Masters
20      40            Private      Doctorate
21      54            Private        HS-grad
22      35        Federal-gov            9th
23      43            Private           11th
24      59            Private        HS-grad
25      56          Local-gov      Bachelors
26      19            Private        HS-grad
27      54                  ?   Some-college
28      39            Private        HS-grad
29      49            Private        HS-grad
...    ...                ...            ...
32531   30                  ?      Bachelors
32532   34            Private      Doctorate
32533   54            Private      Bachelors
32534   37            Private   Some-college
32535   22            Private           12th
32536   34            Private      Bachelors
32537   30            Private        HS-grad
32538   38            Private      Bachelors
32539   71                  ?      Doctorate
32540   45          State-gov        HS-grad
32541   41                  ?        HS-grad
32542   72                  ?        HS-grad
32543   45          Local-gov     Assoc-acdm
32544   31            Private        Masters
32545   39          Local-gov     Assoc-acdm
32546   37            Private     Assoc-acdm
32547   43            Private        HS-grad
32548   65   Self-emp-not-inc    Prof-school
32549   43          State-gov   Some-college
32550   43   Self-emp-not-inc   Some-college
32551   32            Private           10th
32552   43            Private      Assoc-voc
32553   32            Private        Masters
32554   53            Private        Masters
32555   22            Private   Some-college
32556   27            Private     Assoc-acdm
32557   40            Private        HS-grad
32558   58            Private        HS-grad
32559   22            Private        HS-grad
32560   52       Self-emp-inc        HS-grad

[32561 rows x 3 columns]

In [6]:
age=0
for i in range(0,32561):
    age+=df.iloc[i,0]
age=age/32561
print(age)

38.58164675532078

In [10]:
age=0
count=0
for i in range(0,32561):
    age=df.iloc[i,0]
    if(age>40):
        count=count+1
count

13443

In [13]:
df['Age'].mean()

38.58164675532078

In [17]:
(df.loc[df['Age']>40]).shape[0]

13443

In [35]:
df.iloc[20:101,:]

,Age,Workplace,fnlwgt,education,education num,marital-stauts,occupation,relationship,race,sex,captial gain,capital loss,hours per week,native country,Salaray
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
21,54,Private,302146,HS-grad,9,Separated,Other-service,Unmarried,Black,Female,0,0,20,United-States,<=50K
22,35,Federal-gov,76845,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,Male,0,0,40,United-States,<=50K
23,43,Private,117037,11th,7,Married-civ-spouse,Transport-moving,Husband,White,Male,0,2042,40,United-States,<=50K
24,59,Private,109015,HS-grad,9,Divorced,Tech-support,Unmarried,White,Female,0,0,40,United-States,<=50K
25,56,Local-gov,216851,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,40,United-States,>50K
26,19,Private,168294,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K
27,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
29,49,Private,193366,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
30,23,Local-gov,190709,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,Male,0,0,52,United-States,<=50K
31,20,Private,266015,Some-college,10,Never-married,Sales,Own-child,Black,Male,0,0,44,United-States,<=50K
32,45,Private,386940,Bachelors,13,Divorced,Exec-managerial,Own-child,White,Male,0,1408,40,United-States,<=50K
33,30,Federal-gov,59951,Some-college,10,Married-civ-spouse,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
34,22,State-gov,311512,Some-college,10,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,15,United-States,<=50K
35,48,Private,242406,11th,7,Never-married,Machine-op-inspct,Unmarried,White,Male,0,0,40,Puerto-Rico,<=50K
36,21,Private,197200,Some-college,10,Never-married,Machine-op-inspct,Own-child,White,Male,0,0,40,United-States,<=50K
37,19,Private,544091,HS-grad,9,Married-AF-spouse,Adm-clerical,Wife,White,Female,0,0,25,United-States,<=50K
38,31,Private,84154,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,38,?,>50K
39,48,Self-emp-not-inc,265477,Assoc-acdm,12,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
40,31,Private,507875,9th,5,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,43,United-States,<=50K
41,53,Self-emp-not-inc,88506,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
42,24,Private,172987,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,50,United-States,<=50K
43,49,Private,94638,HS-grad,9,Separated,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
44,25,Private,289980,HS-grad,9,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,35,United-States,<=50K
45,57,Federal-gov,337895,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Black,Male,0,0,40,United-States,>50K
46,53,Private,144361,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,38,United-States,<=50K
47,44,Private,128354,Masters,14,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,<=50K
48,41,State-gov,101603,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
49,29,Private,271466,Assoc-voc,11,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,43,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71,31,Private,309974,Bachelors,13,Separated,Sales,Own-child,Black,Female,0,0,40,United-States,<=50K
72,29,Self-emp-not-inc,162298,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,70,United-States,>50K
73,23,Private,211678,Some-college,10,Never-married,Machine-op-inspct,Not-in-family,White,Male,0,0,40,United-States,<=50K
74,79,Private,124744,Some-college,10,Married-civ-spouse,Prof-specialty,Other-relative,White,Male,0,0,20,United-States,<=50K
75,27,Private,213921,HS-grad,9,Never-married,Other-service,Own-child,White,Male,0,0,40,Mexico,<=50K
76,40,Private,32214,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
77,67,?,212759,10th,6,Married-civ-spouse,?,Husband,White,Male,0,0,2,United-States,<=50K
78,18,Private,309634,11th,7,Never-married,Other-service,Own-child,White,Female,0,0,22,United-States,<=50K
79,31,Local-gov,125927,7th-8th,4,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,40,United-States,<=50K
80,18,Private,446839,HS-grad,9,Never-married,Sales,Not-in-family,White,Male,0,0,30,United-States,<=50K
81,52,Private,276515,Bachelors,13,Married-civ-spouse,Other-service,Husband,White,Male,0,0,40,Cuba,<=50K
82,46,Private,51618,HS-grad,9,Married-civ-spouse,Other-service,Wife,White,Female,0,0,40,United-States,<=50K
83,59,Private,159937,HS-grad,9,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,<=50K
84,44,Private,343591,HS-grad,9,Divorced,Craft-repair,Not-in-family,White,Female,14344,0,40,United-States,>50K
85,53,Private,346253,HS-grad,9,Divorced,Sales,Own-child,White,Female,0,0,35,United-States,<=50K
86,49,Local-gov,268234,HS-grad,9,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
87,33,Private,202051,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K
88,30,Private,54334,9th,5,Never-married,Sales,Not-in-family,White,Male,0,0,40,United-States,<=50K
89,43,Federal-gov,410867,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
90,57,Private,249977,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
91,37,Private,286730,Some-college,10,Divorced,Craft-repair,Unmarried,White,Female,0,0,40,United-States,<=50K
92,28,Private,212563,Some-college,10,Divorced,Machine-op-inspct,Unmarried,Black,Female,0,0,25,United-States,<=50K
93,30,Private,117747,HS-grad,9,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,1573,35,?,<=50K
94,34,Local-gov,226296,Bachelors,13,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
95,29,Local-gov,115585,Some-college,10,Never-married,Handlers-cleaners,Not-in-family,White,Male,0,0,50,United-States,<=50K
96,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K
97,37,Private,202683,Some-college,10,Married-civ-spouse,Sales,Husband,White,Male,0,0,48,United-States,>50K
98,48,Private,171095,Assoc-acdm,12,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,England,<=50K
99,32,Federal-gov,249409,HS-grad,9,Never-married,Other-service,Own-child,Black,Male,0,0,40,United-States,<=50K
100,76,Private,124191,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K

In [21]:
print(df[['State-gov']])

KeyError: "None of [Index(['State-gov'], dtype='object')] are in the [columns]"

In [22]:
print(df)

       39          State-gov   77516      Bachelors   13  \
0      50   Self-emp-not-inc   83311      Bachelors   13
1      38            Private  215646        HS-grad    9
2      53            Private  234721           11th    7
3      28            Private  338409      Bachelors   13
4      37            Private  284582        Masters   14
5      49            Private  160187            9th    5
6      52   Self-emp-not-inc  209642        HS-grad    9
7      31            Private   45781        Masters   14
8      42            Private  159449      Bachelors   13
9      37            Private  280464   Some-college   10
10     30          State-gov  141297      Bachelors   13
11     23            Private  122272      Bachelors   13
12     32            Private  205019     Assoc-acdm   12
13     40            Private  121772      Assoc-voc   11
14     34            Private  245487        7th-8th    4
15     25   Self-emp-not-inc  176756        HS-grad    9
16     32            Private  186824        HS-grad    9
17     38            Private   28887           11th    7
18     43   Self-emp-not-inc  292175        Masters   14
19     40            Private  193524      Doctorate   16
20     54            Private  302146        HS-grad    9
21     35        Federal-gov   76845            9th    5
22     43            Private  117037           11th    7
23     59            Private  109015        HS-grad    9
24     56          Local-gov  216851      Bachelors   13
25     19            Private  168294        HS-grad    9
26     54                  ?  180211   Some-college   10
27     39            Private  367260        HS-grad    9
28     49            Private  193366        HS-grad    9
29     23          Local-gov  190709     Assoc-acdm   12
...    ..                ...     ...            ...  ...
32530  30                  ?   33811      Bachelors   13
32531  34            Private  204461      Doctorate   16
32532  54            Private  337992      Bachelors   13
32533  37            Private  179137   Some-college   10
32534  22            Private  325033           12th    8
32535  34            Private  160216      Bachelors   13
32536  30            Private  345898        HS-grad    9
32537  38            Private  139180      Bachelors   13
32538  71                  ?  287372      Doctorate   16
32539  45          State-gov  252208        HS-grad    9
32540  41                  ?  202822        HS-grad    9
32541  72                  ?  129912        HS-grad    9
32542  45          Local-gov  119199     Assoc-acdm   12
32543  31            Private  199655        Masters   14
32544  39          Local-gov  111499     Assoc-acdm   12
32545  37            Private  198216     Assoc-acdm   12
32546  43            Private  260761        HS-grad    9
32547  65   Self-emp-not-inc   99359    Prof-school   15
32548  43          State-gov  255835   Some-college   10
32549  43   Self-emp-not-inc   27242   Some-college   10
32550  32            Private   34066           10th    6
32551  43            Private   84661      Assoc-voc   11
32552  32            Private  116138        Masters   14
32553  53            Private  321865        Masters   14
32554  22            Private  310152   Some-college   10
32555  27            Private  257302     Assoc-acdm   12
32556  40            Private  154374        HS-grad    9
32557  58            Private  151910        HS-grad    9
32558  22            Private  201490        HS-grad    9
32559  52       Self-emp-inc  287927        HS-grad    9

                Never-married        Adm-clerical    Not-in-family  \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse   Handlers-cleaners          Husband
3          Married-civ-spouse      Prof-specialty             Wife
4          Married-civ-spouse     Exec-managerial             Wife
5       Married-spouse-absent       Other-service    Not-in-family
6          Married-civ-spouse     Exec-managerial          Husband
7               Never-married      Prof-specialty    Not-in-family
8          Married-civ-spouse     Exec-managerial          Husband
9          Married-civ-spouse     Exec-managerial          Husband
10         Married-civ-spouse      Prof-specialty          Husband
11              Never-married        Adm-clerical        Own-child
12              Never-married               Sales    Not-in-family
13         Married-civ-spouse        Craft-repair          Husband
14         Married-civ-spouse    Transport-moving          Husband
15              Never-married     Farming-fishing        Own-child
16              Never-married   Machine-op-inspct        Unmarried
17         Married-civ-spouse               Sales          Husband
18                   Divorced     Exec-managerial        Unmarried
19         Married-civ-spouse      Prof-specialty          Husband
20                  Separated       Other-service        Unmarried
21         Married-civ-spouse     Farming-fishing          Husband
22         Married-civ-spouse    Transport-moving          Husband
23                   Divorced        Tech-support        Unmarried
24         Married-civ-spouse        Tech-support          Husband
25              Never-married        Craft-repair        Own-child
26         Married-civ-spouse                   ?          Husband
27                   Divorced     Exec-managerial    Not-in-family
28         Married-civ-spouse        Craft-repair          Husband
29              Never-married     Protective-serv    Not-in-family
...                       ...                 ...              ...
32530           Never-married                   ?    Not-in-family
32531      Married-civ-spouse      Prof-specialty          Husband
32532      Married-civ-spouse     Exec-managerial          Husband
32533                Divorced        Adm-clerical        Unmarried
32534           Never-married     Protective-serv        Own-child
32535           Never-married     Exec-managerial    Not-in-family
32536           Never-married        Craft-repair    Not-in-family
32537                Divorced      Prof-specialty        Unmarried
32538      Married-civ-spouse                   ?          Husband
32539               Separated        Adm-clerical        Own-child
32540               Separated                   ?    Not-in-family
32541      Married-civ-spouse                   ?          Husband
32542                Divorced      Prof-specialty        Unmarried
32543                Divorced       Other-service    Not-in-family
32544      Married-civ-spouse        Adm-clerical             Wife
32545                Divorced        Tech-support    Not-in-family
32546      Married-civ-spouse   Machine-op-inspct          Husband
32547           Never-married      Prof-specialty    Not-in-family
32548                Divorced        Adm-clerical   Other-relative
32549      Married-civ-spouse        Craft-repair          Husband
32550      Married-civ-spouse   Handlers-cleaners          Husband
32551      Married-civ-spouse               Sales          Husband
32552           Never-married        Tech-support    Not-in-family
32553      Married-civ-spouse     Exec-managerial          Husband
32554           Never-married     Protective-serv    Not-in-family
32555      Married-civ-spouse        Tech-support             Wife
32556      Married-civ-spouse   Machine-op-inspct          Husband
32557                 Widowed        Adm-clerical        Unmarried
32558           Never-married        Adm-clerical        Own-child
32559      Married-civ-spouse     Exec-managerial             Wife

                     White     Male   2174     0   40   United-States   <=50K
0                    White     Male      0     0   13   United-States   <=50K
1                    White     Male      0     0   40   United-States   <=50K
2                    Black     Male      0     0   40   United-States   <=50K
3                    Black   Female      0     0   40            Cuba   <=50K
4                    White   Female      0     0   40   United-States   <=50K
5                    Black   Female      0     0   16         Jamaica   <=50K
6                    White     Male      0     0   45   United-States    >50K
7                    White   Female  14084     0   50   United-States    >50K
8                    White     Male   5178     0   40   United-States    >50K
9                    Black     Male      0     0   80   United-States    >50K
10      Asian-Pac-Islander     Male      0     0   40           India    >50K
11                   White   Female      0     0   30   United-States   <=50K
12                   Black     Male      0     0   50   United-States   <=50K
13      Asian-Pac-Islander     Male      0     0   40               ?    >50K
14      Amer-Indian-Eskimo     Male      0     0   45          Mexico   <=50K
15                   White     Male      0     0   35   United-States   <=50K
16                   White     Male      0     0   40   United-States   <=50K
17                   White     Male      0     0   50   United-States   <=50K
18                   White   Female      0     0   45   United-States    >50K
19                   White     Male      0     0   60   United-States    >50K
20                   Black   Female      0     0   20   United-States   <=50K
21                   Black     Male      0     0   40   United-States   <=50K
22                   White     Male      0  2042   40   United-States   <=50K
23                   White   Female      0     0   40   United-States   <=50K
24                   White     Male      0     0   40   United-States    >50K
25                   White     Male      0     0   40   United-States   <=50K
26      Asian-Pac-Islander     Male      0     0   60           South    >50K
27                   White     Male      0     0   80   United-States   <=50K
28                   White     Male      0     0   40   United-States   <=50K
29                   White     Male      0     0   52   United-States   <=50K
...                    ...      ...    ...   ...  ...             ...     ...
32530   Asian-Pac-Islander   Female      0     0   99   United-States   <=50K
32531                White     Male      0     0   60   United-States    >50K
32532   Asian-Pac-Islander     Male      0     0   50           Japan    >50K
32533                White   Female      0     0   39   United-States   <=50K
32534                Black     Male      0     0   35   United-States   <=50K
32535                White   Female      0     0   55   United-States    >50K
32536                Black     Male      0     0   46   United-States   <=50K
32537                Black   Female  15020     0   45   United-States    >50K
32538                White     Male      0     0   10   United-States    >50K
32539                White   Female      0     0   40   United-States   <=50K
32540                Black   Female      0     0   32   United-States   <=50K
32541                White     Male      0     0   25   United-States   <=50K
32542                White   Female      0     0   48   United-States   <=50K
32543                Other   Female      0     0   30   United-States   <=50K
32544                White   Female      0     0   20   United-States    >50K
32545                White   Female      0     0   40   United-States   <=50K
32546                White     Male      0     0   40          Mexico   <=50K
32547                White     Male   1086     0   60   United-States   <=50K
32548                White   Female      0     0   40   United-States   <=50K
32549                White     Male      0     0   50   United-States   <=50K
32550   Amer-Indian-Eskimo     Male      0     0   40   United-States   <=50K
32551                White     Male      0     0   45   United-States   <=50K
32552   Asian-Pac-Islander     Male      0     0   11          Taiwan   <=50K
32553                White     Male      0     0   40   United-States    >50K
32554                White     Male      0     0   40   United-States   <=50K
32555                White   Female      0     0   38   United-States   <=50K
32556                White     Male      0     0   40   United-States    >50K
32557                White   Female      0     0   40   United-States   <=50K
32558                White     Male      0     0   20   United-States   <=50K
32559                White   Female  15024     0   40   United-States    >50K

[32560 rows x 15 columns]

In [23]:
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}

In [24]:
d=pd.DataFrame(data)

In [25]:
print(d)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [26]:
print(df[['age','workclass']])

KeyError: "None of [Index(['age', 'workclass'], dtype='object')] are in the [columns]"

In [27]:
print(df)

       39          State-gov   77516      Bachelors   13  \
0      50   Self-emp-not-inc   83311      Bachelors   13
1      38            Private  215646        HS-grad    9
2      53            Private  234721           11th    7
3      28            Private  338409      Bachelors   13
4      37            Private  284582        Masters   14
5      49            Private  160187            9th    5
6      52   Self-emp-not-inc  209642        HS-grad    9
7      31            Private   45781        Masters   14
8      42            Private  159449      Bachelors   13
9      37            Private  280464   Some-college   10
10     30          State-gov  141297      Bachelors   13
11     23            Private  122272      Bachelors   13
12     32            Private  205019     Assoc-acdm   12
13     40            Private  121772      Assoc-voc   11
14     34            Private  245487        7th-8th    4
15     25   Self-emp-not-inc  176756        HS-grad    9
16     32            Private  186824        HS-grad    9
17     38            Private   28887           11th    7
18     43   Self-emp-not-inc  292175        Masters   14
19     40            Private  193524      Doctorate   16
20     54            Private  302146        HS-grad    9
21     35        Federal-gov   76845            9th    5
22     43            Private  117037           11th    7
23     59            Private  109015        HS-grad    9
24     56          Local-gov  216851      Bachelors   13
25     19            Private  168294        HS-grad    9
26     54                  ?  180211   Some-college   10
27     39            Private  367260        HS-grad    9
28     49            Private  193366        HS-grad    9
29     23          Local-gov  190709     Assoc-acdm   12
...    ..                ...     ...            ...  ...
32530  30                  ?   33811      Bachelors   13
32531  34            Private  204461      Doctorate   16
32532  54            Private  337992      Bachelors   13
32533  37            Private  179137   Some-college   10
32534  22            Private  325033           12th    8
32535  34            Private  160216      Bachelors   13
32536  30            Private  345898        HS-grad    9
32537  38            Private  139180      Bachelors   13
32538  71                  ?  287372      Doctorate   16
32539  45          State-gov  252208        HS-grad    9
32540  41                  ?  202822        HS-grad    9
32541  72                  ?  129912        HS-grad    9
32542  45          Local-gov  119199     Assoc-acdm   12
32543  31            Private  199655        Masters   14
32544  39          Local-gov  111499     Assoc-acdm   12
32545  37            Private  198216     Assoc-acdm   12
32546  43            Private  260761        HS-grad    9
32547  65   Self-emp-not-inc   99359    Prof-school   15
32548  43          State-gov  255835   Some-college   10
32549  43   Self-emp-not-inc   27242   Some-college   10
32550  32            Private   34066           10th    6
32551  43            Private   84661      Assoc-voc   11
32552  32            Private  116138        Masters   14
32553  53            Private  321865        Masters   14
32554  22            Private  310152   Some-college   10
32555  27            Private  257302     Assoc-acdm   12
32556  40            Private  154374        HS-grad    9
32557  58            Private  151910        HS-grad    9
32558  22            Private  201490        HS-grad    9
32559  52       Self-emp-inc  287927        HS-grad    9

                Never-married        Adm-clerical    Not-in-family  \
0          Married-civ-spouse     Exec-managerial          Husband
1                    Divorced   Handlers-cleaners    Not-in-family
2          Married-civ-spouse   Handlers-cleaners          Husband
3          Married-civ-spouse      Prof-specialty             Wife
4          Married-civ-spouse     Exec-managerial             Wife
5       Married-spouse-absent       Other-service    Not-in-family
6          Married-civ-spouse     Exec-managerial          Husband
7               Never-married      Prof-specialty    Not-in-family
8          Married-civ-spouse     Exec-managerial          Husband
9          Married-civ-spouse     Exec-managerial          Husband
10         Married-civ-spouse      Prof-specialty          Husband
11              Never-married        Adm-clerical        Own-child
12              Never-married               Sales    Not-in-family
13         Married-civ-spouse        Craft-repair          Husband
14         Married-civ-spouse    Transport-moving          Husband
15              Never-married     Farming-fishing        Own-child
16              Never-married   Machine-op-inspct        Unmarried
17         Married-civ-spouse               Sales          Husband
18                   Divorced     Exec-managerial        Unmarried
19         Married-civ-spouse      Prof-specialty          Husband
20                  Separated       Other-service        Unmarried
21         Married-civ-spouse     Farming-fishing          Husband
22         Married-civ-spouse    Transport-moving          Husband
23                   Divorced        Tech-support        Unmarried
24         Married-civ-spouse        Tech-support          Husband
25              Never-married        Craft-repair        Own-child
26         Married-civ-spouse                   ?          Husband
27                   Divorced     Exec-managerial    Not-in-family
28         Married-civ-spouse        Craft-repair          Husband
29              Never-married     Protective-serv    Not-in-family
...                       ...                 ...              ...
32530           Never-married                   ?    Not-in-family
32531      Married-civ-spouse      Prof-specialty          Husband
32532      Married-civ-spouse     Exec-managerial          Husband
32533                Divorced        Adm-clerical        Unmarried
32534           Never-married     Protective-serv        Own-child
32535           Never-married     Exec-managerial    Not-in-family
32536           Never-married        Craft-repair    Not-in-family
32537                Divorced      Prof-specialty        Unmarried
32538      Married-civ-spouse                   ?          Husband
32539               Separated        Adm-clerical        Own-child
32540               Separated                   ?    Not-in-family
32541      Married-civ-spouse                   ?          Husband
32542                Divorced      Prof-specialty        Unmarried
32543                Divorced       Other-service    Not-in-family
32544      Married-civ-spouse        Adm-clerical             Wife
32545                Divorced        Tech-support    Not-in-family
32546      Married-civ-spouse   Machine-op-inspct          Husband
32547           Never-married      Prof-specialty    Not-in-family
32548                Divorced        Adm-clerical   Other-relative
32549      Married-civ-spouse        Craft-repair          Husband
32550      Married-civ-spouse   Handlers-cleaners          Husband
32551      Married-civ-spouse               Sales          Husband
32552           Never-married        Tech-support    Not-in-family
32553      Married-civ-spouse     Exec-managerial          Husband
32554           Never-married     Protective-serv    Not-in-family
32555      Married-civ-spouse        Tech-support             Wife
32556      Married-civ-spouse   Machine-op-inspct          Husband
32557                 Widowed        Adm-clerical        Unmarried
32558           Never-married        Adm-clerical        Own-child
32559      Married-civ-spouse     Exec-managerial             Wife

                     White     Male   2174     0   40   United-States   <=50K
0                    White     Male      0     0   13   United-States   <=50K
1                    White     Male      0     0   40   United-States   <=50K
2                    Black     Male      0     0   40   United-States   <=50K
3                    Black   Female      0     0   40            Cuba   <=50K
4                    White   Female      0     0   40   United-States   <=50K
5                    Black   Female      0     0   16         Jamaica   <=50K
6                    White     Male      0     0   45   United-States    >50K
7                    White   Female  14084     0   50   United-States    >50K
8                    White     Male   5178     0   40   United-States    >50K
9                    Black     Male      0     0   80   United-States    >50K
10      Asian-Pac-Islander     Male      0     0   40           India    >50K
11                   White   Female      0     0   30   United-States   <=50K
12                   Black     Male      0     0   50   United-States   <=50K
13      Asian-Pac-Islander     Male      0     0   40               ?    >50K
14      Amer-Indian-Eskimo     Male      0     0   45          Mexico   <=50K
15                   White     Male      0     0   35   United-States   <=50K
16                   White     Male      0     0   40   United-States   <=50K
17                   White     Male      0     0   50   United-States   <=50K
18                   White   Female      0     0   45   United-States    >50K
19                   White     Male      0     0   60   United-States    >50K
20                   Black   Female      0     0   20   United-States   <=50K
21                   Black     Male      0     0   40   United-States   <=50K
22                   White     Male      0  2042   40   United-States   <=50K
23                   White   Female      0     0   40   United-States   <=50K
24                   White     Male      0     0   40   United-States    >50K
25                   White     Male      0     0   40   United-States   <=50K
26      Asian-Pac-Islander     Male      0     0   60           South    >50K
27                   White     Male      0     0   80   United-States   <=50K
28                   White     Male      0     0   40   United-States   <=50K
29                   White     Male      0     0   52   United-States   <=50K
...                    ...      ...    ...   ...  ...             ...     ...
32530   Asian-Pac-Islander   Female      0     0   99   United-States   <=50K
32531                White     Male      0     0   60   United-States    >50K
32532   Asian-Pac-Islander     Male      0     0   50           Japan    >50K
32533                White   Female      0     0   39   United-States   <=50K
32534                Black     Male      0     0   35   United-States   <=50K
32535                White   Female      0     0   55   United-States    >50K
32536                Black     Male      0     0   46   United-States   <=50K
32537                Black   Female  15020     0   45   United-States    >50K
32538                White     Male      0     0   10   United-States    >50K
32539                White   Female      0     0   40   United-States   <=50K
32540                Black   Female      0     0   32   United-States   <=50K
32541                White     Male      0     0   25   United-States   <=50K
32542                White   Female      0     0   48   United-States   <=50K
32543                Other   Female      0     0   30   United-States   <=50K
32544                White   Female      0     0   20   United-States    >50K
32545                White   Female      0     0   40   United-States   <=50K
32546                White     Male      0     0   40          Mexico   <=50K
32547                White     Male   1086     0   60   United-States   <=50K
32548                White   Female      0     0   40   United-States   <=50K
32549                White     Male      0     0   50   United-States   <=50K
32550   Amer-Indian-Eskimo     Male      0     0   40   United-States   <=50K
32551                White     Male      0     0   45   United-States   <=50K
32552   Asian-Pac-Islander     Male      0     0   11          Taiwan   <=50K
32553                White     Male      0     0   40   United-States    >50K
32554                White     Male      0     0   40   United-States   <=50K
32555                White   Female      0     0   38   United-States   <=50K
32556                White     Male      0     0   40   United-States    >50K
32557                White   Female      0     0   40   United-States   <=50K
32558                White     Male      0     0   20   United-States   <=50K
32559                White   Female  15024     0   40   United-States    >50K

[32560 rows x 15 columns]

In [28]:
data = pd.read_csv("adult.data", index_col ="age")

ValueError: Index age invalid